language: objective-c

before_install:
  - brew update

install:
  - mkdir -p $(brew --repo)/Library/Taps/travis
  - ln -s $PWD $(brew --repo)/Library/Taps/travis/qt@4
  - brew tap --repair

script:
  - brew audit qt@4
  - brew install qt@4
  - brew test qt@4
